name:                advent-of-code
version:             0.1.0.0
github:              "callum-oakley/advent-of-code-2019"
license:             BSD3
author:              "Callum Oakley"
maintainer:          "c.oakley108@gmail.com"
copyright:           "2019 Callum Oakley"

ghc-options:
- -Wall
- -Wno-incomplete-patterns
- -Wno-type-defaults
- -fobject-code
- -O

dependencies:
- base >= 4.7 && < 5
- tasty
- tasty-hunit
- tasty-quickcheck
- split
- vector
- containers
- mtl
- stm
- async
- QuickCheck
- array
- sort
- linear
- parsec

library:
  source-dirs: src

tests:
  advent-of-code-test:
    main: Test.hs
    source-dirs: test
    dependencies:
    - advent-of-code
